name: fraud-detection
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.23,<2.0
  - pandas>=1.5,<3.0
  - scikit-learn==1.7.0
  - xgboost==2.0.3
  - joblib>=1.2,<2.0
  - pip
  - pip:
      - streamlit
      - gdown